version: 0.1
   
environment_variables:
  plaintext:
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8
phases:
  install:
    commands:
      - gem install jekyll bundler
      - bundle update
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://taylorcreekbaum.com